name: build_jazzy_docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]

jobs:
  build_jazzy_docs:

    runs-on: macos-latest

    steps:
      uses: sersoft-gmbh/swifty-docs-action@v1
      with:
        # Optional. Defaults to ${{github.workspace}}.
        source: ${{github.workspace}}
        # Optional. E.g. run this action on tags and use the tag name.
        module-version: 1.2.3
        # Optional.
        output: docs
        # Optional. Defaults to true.
        clean: true
